### ISSUE TITLE
Incomplete milestone v1.1 requirements

### ISSUE THREAD

**Issue by yaowei-soc** [AY2021S2-CS2103T-T12-3/tp#61]
![image](https://user-images.githubusercontent.com/77482180/110069473-d53b0e00-7db2-11eb-95a7-92615f6a1b65.png)

We need to remove all traces of AB3 and update the necessary files

Things to be done:

- [x] README
- [x] docs/AboutUs.md
- [x] docs/_config.yml
- [x] docs/UserGuide (no traces of AB3)
- [x] docs/DeveloperGuide  (no traces of AB3)

**Comment by yaowei-soc** [comment]
![image](https://user-images.githubusercontent.com/77482180/110218596-8944b200-7ef5-11eb-85f8-0a43ef204727.png)

Seems like the changes in PR #65 are working. I have closed the v1.1 milestone since there's no more issues related to it.
